### ISSUE TITLE
Cannot launch the plugin on Debian 10

### ISSUE THREAD

**Issue by MaximeMaW** [oeway/DPNUnet-Segmentation#10]
Hello. I am trying to use this plugin, but I am getting the following error when I try to activate the plugin: 
```
﻿error:error:info:info:info:info:info:info:info:info:info:info:info:undefined:undefined:undefined
undefined
Cloning repo https://github.com/oeway/DPNUnet-Segmentation to /home/umr3664/ImJoyWorkspace/default/DPNUnet-Segmentation
Running env command: conda create -y -n dsb2018-gpu python=3.6.8
Successful execution of env command
Running requirements subprocess(pid=716): /bin/bash -c 'source /data/CoulonLab/software/anaconda3/bin/activate dsb2018-gpu && pip install descartes palettable geojson read-roi gputil namedlist'
Running requirements subprocess(pid=792): /bin/bash -c 'source /data/CoulonLab/software/anaconda3/bin/activate dsb2018-gpu && pip install lightgbm imgaug pandas imageio'
Running requirements subprocess(pid=1023): /bin/bash -c 'source /data/CoulonLab/software/anaconda3/bin/activate dsb2018-gpu && conda install -y opencv tqdm scipy=1.0.0'
Running requirements subprocess(pid=1927): /bin/bash -c 'source /data/CoulonLab/software/anaconda3/bin/activate dsb2018-gpu && conda install -y pytorch=0.4.1 torchvision==0.2.0 cuda90 -c pytorch'
Running requirements subprocess(pid=2466): /bin/bash -c 'source /data/CoulonLab/software/anaconda3/bin/activate dsb2018-gpu && pip install tensorboardX'
Running requirements subprocess(pid=2487): /bin/bash -c 'source /data/CoulonLab/software/anaconda3/bin/activate dsb2018-gpu && pip install imjoy[worker]==0.8.22'
Requirements command executed successfully.
Running subprocess (pid=2512) with /bin/bash -c 'source /data/CoulonLab/software/anaconda3/bin/activate dsb2018-gpu && python -m imjoy.workers.python_worker --id="DPNUnet_dux2ca59wc" --server=http://127.0.0.1:9527 --secret="a9b066f6-97ce-432f-9547-63ccc7750c81"'
Plugin process exited with code 1
Traceback (most recent call last):
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/site-packages/imjoy/workers/python_worker.py", line 519, in <module>
    main()
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/site-packages/imjoy/workers/python_worker.py", line 515, in main
    plugin_conn.start()
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/site-packages/imjoy/workers/python_worker.py", line 118, in start
    self.setup()
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/site-packages/imjoy/workers/python_worker.py", line 106, in setup
    self.client.setup(self)
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/site-packages/imjoy/workers/python_client.py", line 181, in setup
    self.sio.connect(conn.opt.server)
  File "/data/CoulonLab/software/anaconda3/envs/dsb2018-gpu/lib/python3.6/site-packages/socketio/client.py", line 246, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Unexpected status code 502 in server response

Plugin process exited with code 1
```

Would you have any pointer, I have no idea where to start :s. 

Many thanks Wei!

**Comment by oeway** [comment]
Hi, it seems that the dependencies are not correctly installed. From the log, you should have `conda create -y -n dsb2018-gpu python=3.6.8` and several requirements. Could you manually check if those requirements are installed in `dsb2018-gpu`? See also here: https://imjoy.io/docs/#/development?id=access-plugin-engine-from-command-line

Or also try with a simpler plugin:
https://imjoy.io/docs/#/tutorials?id=making-a-plugin-for-segmentation-with-u-net

**Comment by oeway** [comment]
And also, this plugin only works with GPU. I have already a cleaner version
for cpu, I will try to find a time in the following days to make a simple
plugin.

**Comment by MaximeMaW** [comment]
Thanks a lot for your reply! I realized that I had intermittent problems with the GPU, so this might be the reason why the plugin fails. Until we get this fixed, I would be happy to get the CPU-only version. Good luck and many thanks for your responsive support!
