### ISSUE TITLE
Cannot launch the plugin

### ISSUE THREAD

**Issue by Padoup-Padoup** [oeway/DPNUnet-Segmentation#9]
Hi @oeway,

I just tried to open the DPNUnet plugin in Imjoy, and I am getting the
following error in the Plugin Engine console. Can you reproduce the
problem? Could you tell me what kind of information you would need me to
provide?

Here is the log from the plugin engine console:

```
INFO:ImJoyPluginEngine:Initialize the plugin, name=DPNUnet, id=DPNUnet_bwqzk5on9c, cmd=python, worksp
ace=default
INFO:ImJoyPluginEngine:Cloning repo https://github.com/oeway/DPNUnet-Segmentation to C:\Users\Coulon_
team/ImJoyWorkspace\default\DPNUnet-Segmentation
INFO:ImJoyPluginEngine:Running env command: conda create -y -n dsb2018-gpu python=3.6.8
INFO:ImJoyPluginEngine:Running command ['conda', 'create', '-y', '-n', 'dsb2018-gpu', 'python=3.6.8']

Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Coulon_team\Anaconda3\envs\dsb2018-gpu

  added / updated specs:
    - python=3.6.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.9.11          |           py36_0         155 KB
    pip-19.2.3                 |           py36_0         1.9 MB
    python-3.6.8               |       h9f7ef89_7        20.3 MB
    setuptools-41.2.0          |           py36_0         685 KB
    wheel-0.33.6               |           py36_0          58 KB
    wincertstore-0.2           |   py36h7fe50ca_0          13 KB
    ------------------------------------------------------------
                                           Total:        23.1 MB

The following NEW packages will be INSTALLED:

  certifi            pkgs/main/win-64::certifi-2019.9.11-py36_0
  pip                pkgs/main/win-64::pip-19.2.3-py36_0
  python             pkgs/main/win-64::python-3.6.8-h9f7ef89_7
  setuptools         pkgs/main/win-64::setuptools-41.2.0-py36_0
  sqlite             pkgs/main/win-64::sqlite-3.29.0-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_0
  wheel              pkgs/main/win-64::wheel-0.33.6-py36_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py36h7fe50ca_0



Downloading and Extracting Packages
setuptools-41.2.0    | 685 KB    |                                                           |   0%
wincertstore-0.2     | 13 KB     |                                                           |   0%
certifi-2019.9.11    | 155 KB    |                                                           |   0%
pip-19.2.3           | 1.9 MB    |                                                           |   0%
wheel-0.33.6         | 58 KB     |                                                           |   0%
python-3.6.8         | 20.3 MB   |                                                           |   0%
INFO:ImJoyPluginEngine:Running requirements commands: ['activate dsb2018-gpu && pip install descartes
 palettable geojson read-roi gputil namedlist', 'activate dsb2018-gpu && pip install lightgbm imgaug
pandas imageio', 'activate dsb2018-gpu && conda install -y opencv tqdm scipy=1.0.0', 'activate dsb201
8-gpu && conda install -y pytorch=0.4.1 torchvision==0.2.0 cuda90 -c pytorch', 'activate dsb2018-gpu
&& pip install tensorboardX', 'activate dsb2018-gpu && pip install imjoy[worker]==0.8.22']
Running command: activate dsb2018-gpu && pip install descartes palettable geojson read-roi gputil nam
edlist
Requirement already satisfied: descartes in c:\users\coulon_team\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: palettable in c:\users\coulon_team\anaconda3\lib\site-packages (3.3.0)

Requirement already satisfied: geojson in c:\users\coulon_team\anaconda3\lib\site-packages (2.5.0)
Requirement already satisfied: read-roi in c:\users\coulon_team\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: gputil in c:\users\coulon_team\anaconda3\lib\site-packages (1.4.0)
Requirement already satisfied: namedlist in c:\users\coulon_team\anaconda3\lib\site-packages (1.7)
Requirement already satisfied: matplotlib in c:\users\coulon_team\anaconda3\lib\site-packages (from d
escartes) (2.2.3)
Requirement already satisfied: numpy>=1.7.1 in c:\users\coulon_team\anaconda3\lib\site-packages (from
 matplotlib->descartes) (1.15.1)
Requirement already satisfied: cycler>=0.10 in c:\users\coulon_team\anaconda3\lib\site-packages (from
 matplotlib->descartes) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\coulon_team\anaco
nda3\lib\site-packages (from matplotlib->descartes) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\coulon_team\anaconda3\lib\site-packag
es (from matplotlib->descartes) (2.7.3)
Requirement already satisfied: pytz in c:\users\coulon_team\anaconda3\lib\site-packages (from matplot
lib->descartes) (2018.5)
Requirement already satisfied: six>=1.10 in c:\users\coulon_team\anaconda3\lib\site-packages (from ma
tplotlib->descartes) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\coulon_team\anaconda3\lib\site-packages
(from matplotlib->descartes) (1.0.1)
Requirement already satisfied: setuptools in c:\users\coulon_team\anaconda3\lib\site-packages (from k
iwisolver>=1.0.1->matplotlib->descartes) (40.2.0)
Running command: activate dsb2018-gpu && pip install lightgbm imgaug pandas imageio
Collecting lightgbm
  Using cached https://files.pythonhosted.org/packages/c7/0b/a183c06e7778893b2f12bb3e2cdab57f142b4e49
cd25cc643047f714e74c/lightgbm-2.3.0-py2.py3-none-win_amd64.whl
Collecting imgaug
  Using cached https://files.pythonhosted.org/packages/11/df/5a3bba95b4600d5ca7aff072082ef0d9837056dd
28cc4e738e7ce88dd8f8/imgaug-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: pandas in c:\users\coulon_team\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied: imageio in c:\users\coulon_team\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: scikit-learn in c:\users\coulon_team\anaconda3\lib\site-packages (from
 lightgbm) (0.19.2)
Requirement already satisfied: scipy in c:\users\coulon_team\anaconda3\lib\site-packages (from lightg
bm) (1.1.0)
Requirement already satisfied: numpy in c:\users\coulon_team\anaconda3\lib\site-packages (from lightg
bm) (1.15.1)
Requirement already satisfied: Pillow in c:\users\coulon_team\anaconda3\lib\site-packages (from imgau
g) (5.2.0)
Requirement already satisfied: matplotlib in c:\users\coulon_team\anaconda3\lib\site-packages (from i
mgaug) (2.2.3)
Requirement already satisfied: six in c:\users\coulon_team\anaconda3\lib\site-packages (from imgaug)
(1.11.0)
Collecting scikit-image>=0.14.2 (from imgaug)
  Using cached https://files.pythonhosted.org/packages/79/16/c5a36a03f90d4a246791d4ff1879f1868e1c5db5
8fac9f03427395c5e2d6/scikit_image-0.15.0-cp37-none-win_amd64.whl
Collecting Shapely (from imgaug)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89
029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
ERROR:ImJoyPluginEngine:Failed to setup plugin virtual environment or its requirements: Traceback (mo
st recent call last):
  File "c:\users\coulon_team\anaconda3\lib\site-packages\imjoy\runners\subprocess.py", line 729, in l
aunch_plugin
    logging_callback,
  File "c:\users\coulon_team\anaconda3\lib\site-packages\imjoy\runners\helper.py", line 99, in instal
l_reqs
    fail_install()
  File "c:\users\coulon_team\anaconda3\lib\site-packages\imjoy\runners\helper.py", line 71, in fail_i
nstall
    f"Failed to install dependencies with exit code {code} and error: {errors}"
Exception: Failed to install dependencies with exit code 1 and error: b'Could not find conda environm
ent: dsb2018-gpu\r\nYou can list all discoverable environments with `conda info --envs`.\r\n\r\n    E
RROR: Command errored out with exit status 1:\r\n     command: \'c:\\users\\coulon_team\\anaconda3\\p
ython.exe\' -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'C:\\\\Users\\\\COULON~1\\\\A
ppData\\\\Local\\\\Temp\\\\pip-install-9ta87otg\\\\Shapely\\\\setup.py\'"\'"\'; __file__=\'"\'"\'C:\\
\\Users\\\\COULON~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ta87otg\\\\Shapely\\\\setup.py\'"\'"\
';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'
"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --
egg-base pip-egg-info\r\n         cwd: C:\\Users\\COULON~1\\AppData\\Local\\Temp\\pip-install-9ta87ot
g\\Shapely\\\r\n    Complete output (9 lines):\r\n    Traceback (most recent call last):\r\n      Fil
e "<string>", line 1, in <module>\r\n      File "C:\\Users\\COULON~1\\AppData\\Local\\Temp\\pip-insta
ll-9ta87otg\\Shapely\\setup.py", line 80, in <module>\r\n        from shapely._buildcfg import geos_v
ersion_string, geos_version, \\\r\n      File "C:\\Users\\COULON~1\\AppData\\Local\\Temp\\pip-install
-9ta87otg\\Shapely\\shapely\\_buildcfg.py", line 200, in <module>\r\n        lgeos = CDLL("geos_c.dll
")\r\n      File "c:\\users\\coulon_team\\anaconda3\\lib\\ctypes\\__init__.py", line 356, in __init__
\r\n        self._handle = _dlopen(self._name, mode)\r\n    OSError: [WinError 126] The specified mod
ule could not be found\r\n    ----------------------------------------\r\nERROR: Command errored out
with exit status 1: python setup.py egg_info Check the logs for full command output.\r\n'

INFO:ImJoyPluginEngine:Disconnecting from plugin (success: False, message: Plugin process failed to s
tart: Traceback (most recent call last):
  File "c:\users\coulon_team\anaconda3\lib\site-packages\imjoy\runners\subprocess.py", line 729, in l
aunch_plugin
    logging_callback,
  File "c:\users\coulon_team\anaconda3\lib\site-packages\imjoy\runners\helper.py", line 99, in instal
l_reqs
    fail_install()
  File "c:\users\coulon_team\anaconda3\lib\site-packages\imjoy\runners\helper.py", line 71, in fail_i
nstall
    f"Failed to install dependencies with exit code {code} and error: {errors}"
Exception: Failed to install dependencies with exit code 1 and error: b'Could not find conda environm
ent: dsb2018-gpu\r\nYou can list all discoverable environments with `conda info --envs`.\r\n\r\n    E
RROR: Command errored out with exit status 1:\r\n     command: \'c:\\users\\coulon_team\\anaconda3\\p
ython.exe\' -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'C:\\\\Users\\\\COULON~1\\\\A
ppData\\\\Local\\\\Temp\\\\pip-install-9ta87otg\\\\Shapely\\\\setup.py\'"\'"\'; __file__=\'"\'"\'C:\\
\\Users\\\\COULON~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ta87otg\\\\Shapely\\\\setup.py\'"\'"\
';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'
"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --
egg-base pip-egg-info\r\n         cwd: C:\\Users\\COULON~1\\AppData\\Local\\Temp\\pip-install-9ta87ot
g\\Shapely\\\r\n    Complete output (9 lines):\r\n    Traceback (most recent call last):\r\n      Fil
e "<string>", line 1, in <module>\r\n      File "C:\\Users\\COULON~1\\AppData\\Local\\Temp\\pip-insta
ll-9ta87otg\\Shapely\\setup.py", line 80, in <module>\r\n        from shapely._buildcfg import geos_v
ersion_string, geos_version, \\\r\n      File "C:\\Users\\COULON~1\\AppData\\Local\\Temp\\pip-install
-9ta87otg\\Shapely\\shapely\\_buildcfg.py", line 200, in <module>\r\n        lgeos = CDLL("geos_c.dll
")\r\n      File "c:\\users\\coulon_team\\anaconda3\\lib\\ctypes\\__init__.py", line 356, in __init__
\r\n        self._handle = _dlopen(self._name, mode)\r\n    OSError: [WinError 126] The specified mod
ule could not be found\r\n    ----------------------------------------\r\nERROR: Command errored out
with exit status 1: python setup.py egg_info Check the logs for full command output.\r\n'
)
```

Any help would be very appreciated!

**Comment by oeway** [comment]
Hi, thanks for the report.

For the plugin, I only tested on Ubuntu with GPU.

Unfortunately, i don’t have a windows machine with GPU here.
@muellerflorian have you ever tried on a window machine? Maybe you can take
a look see if you can reproduce it?

Also, we have some ongoing work on improving the DPN code base to work with
the latest Pytorch and on GPU. I will try to make that available in a two
or three days so you can test that.

**Comment by Padoup-Padoup** [comment]
Hi,

Thank you for the report, I also wish I had a more standard machine to
work with. I would be happy to test the improved DPN code base with
Pytorch, please keep me posted!

I will keep the ticket open until I can confirm that the issue is
specific to this machine and not to all Windows machines.

**Comment by oeway** [comment]
Hi @Padoup-Padoup , sorry that I am distracted by some other stuff and not having time to finish the new DPNUnet version, but I am working on that, will let you know once I have it running. 
In the meantime, would you mind to tell me that whether you would like to train on your own images or just try to use our pretrained model?
